augmentation:
  train:
    augs:
    - class_name: albumentations.augmentations.transforms.HorizontalFlip
      params:
        p: 0.5
    - class_name: albumentations.augmentations.transforms.RandomBrightnessContrast
      params:
        p: 0.3
    - class_name: albumentations.augmentations.transforms.Normalize
      params:
        p: 1.0
    - class_name: albumentations.pytorch.transforms.ToTensorV2
      params:
        p: 1.0

    bbox_params:
      format: pascal_voc
      label_fields:
        - labels

  valid:
    augs:
      - class_name: albumentations.augmentations.transforms.Normalize
        params:
            p: 1.0
      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
            p: 1.0

    bbox_params:
      format: pascal_voc
      label_fields:
        - labels

